---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apis
  labels:
    app: apis
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: apis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: apis
    spec:
      imagePullSecrets:
      - name: image-pull-secret
      containers:
      - name: apis
        image: registry.versonium.cloud/ps-info/apis:v0.1.3
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        envFrom:
        - configMapRef:
            name: apis-env
      terminationGracePeriodSeconds: 180