apiVersion: v1
kind: PersistentVolume
metadata:
  name: sql-server-data
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/persistent-volumnes/ps-info/sql-server-data"