---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sql-server
  labels:
    app: sql-server
spec:
  serviceName: "sql-server"
  replicas: 1
  selector:
    matchLabels:
      app: sql-server
  template:
    metadata:
      labels:
        app: sql-server
    spec:
      imagePullSecrets:
        - name: image-pull-secret
      containers:
        - name: sql-server
          image: mcr.microsoft.com/mssql/server:2022-latest
          imagePullPolicy: Always
          ports:
            - containerPort: 1433
          envFrom:
            - configMapRef:
                name: sql-server-env
            - secretRef:
                name: sql-server-secrets
          volumeMounts:
            - name: zortracks-psinfo-apphost-09e125ffce-sql-server-data
              mountPath: /var/opt/mssql
  volumeClaimTemplates:
    - metadata:
        name: zortracks-psinfo-apphost-09e125ffce-sql-server-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
