---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ps-info-database-migrations
  labels:
    app: ps-info-database-migrations
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: ps-info-database-migrations
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ps-info-database-migrations
    spec:
      imagePullSecrets:
      - name: image-pull-secret
      containers:
      - name: ps-info-database-migrations
        image: registry.versonium.cloud/ps-info/ps-info-database-migrations:v0.1.3
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: ps-info-database-migrations-env
        - secretRef:
            name: ps-info-database-migrations-secrets
      terminationGracePeriodSeconds: 180