//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zortracks.PsInfo.Application.Host.Areas.Home.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomeLocalizations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeLocalizations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zortracks.PsInfo.Application.Host.Areas.Home.Resources.HomeLocalizations", typeof(HomeLocalizations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sauvegarde des données de vos collaborateurs et restauration en cas de panne de votre système..
        /// </summary>
        public static string Backup_Description {
            get {
                return ResourceManager.GetString("Backup_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sauvegarde.
        /// </summary>
        public static string Backup_Title {
            get {
                return ResourceManager.GetString("Backup_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation et configuration d&apos;équiements informatique : ordinateurs fixes et portables, serveurs d&apos;entreprise, imprimantes, bornes Wi-Fi, vidéo projecteur....
        /// </summary>
        public static string Equipment_Description {
            get {
                return ResourceManager.GetString("Equipment_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipement.
        /// </summary>
        public static string Equipment_Title {
            get {
                return ResourceManager.GetString("Equipment_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entretien et suivi du parc informatique pour un diagnostic immédiat. Assistance téléphonique du lundi au vendredi de 8h30 à 20h incluse..
        /// </summary>
        public static string Outsourcing_Description {
            get {
                return ResourceManager.GetString("Outsourcing_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infogérance.
        /// </summary>
        public static string Outsourcing_Title {
            get {
                return ResourceManager.GetString("Outsourcing_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intervention sur site lorsque la prise en main à distance n&apos;est pas possible ou que l&apos;opération nécéssite une mise hors réseau lors..
        /// </summary>
        public static string Section_ReadyToUse_MoveToSite_Description {
            get {
                return ResourceManager.GetString("Section_ReadyToUse_MoveToSite_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intervention sur site.
        /// </summary>
        public static string Section_ReadyToUse_MoveToSite_Title {
            get {
                return ResourceManager.GetString("Section_ReadyToUse_MoveToSite_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prise en main à distance sur votre infrastructure..
        /// </summary>
        public static string Section_ReadyToUse_Outsourcing_Description {
            get {
                return ResourceManager.GetString("Section_ReadyToUse_Outsourcing_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Télémaintenance.
        /// </summary>
        public static string Section_ReadyToUse_Outsourcing_Title {
            get {
                return ResourceManager.GetString("Section_ReadyToUse_Outsourcing_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistance téléphone pour problème concernant votre activité : coupure Internet, envoie et réception d&apos;emails, maintenance informatique, dépannage bureautique....
        /// </summary>
        public static string Section_ReadyToUse_PhoneAssist_Description {
            get {
                return ResourceManager.GetString("Section_ReadyToUse_PhoneAssist_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistance téléphonique.
        /// </summary>
        public static string Section_ReadyToUse_PhoneAssist_Title {
            get {
                return ResourceManager.GetString("Section_ReadyToUse_PhoneAssist_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une solution.
        /// </summary>
        public static string Section_ReadyToUse_Title_0 {
            get {
                return ResourceManager.GetString("Section_ReadyToUse_Title_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adaptée à vos besoins....
        /// </summary>
        public static string Section_ReadyToUse_Title_1 {
            get {
                return ResourceManager.GetString("Section_ReadyToUse_Title_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solutions de sécurité et protection du réseau informatique d’entreprise. Pare-feu, antivirus et outils de protection de données pour assurer la sérénité de votre activité..
        /// </summary>
        public static string Security_Description {
            get {
                return ResourceManager.GetString("Security_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sécurité.
        /// </summary>
        public static string Security_Title {
            get {
                return ResourceManager.GetString("Security_Title", resourceCulture);
            }
        }
    }
}
